In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/gateway47/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
#vectors
string = tf.Variable("String", tf.string)
integer = tf.Variable(34, tf.int16)

#### Rank of Tensors
The number of dimensions involved in a tensor

In [5]:
tensor1 = tf.Variable(['one','two','three'], tf.string)
tensor2 = tf.Variable([["vec1","vec2"],["vec3","vec4"]], tf.string)

In [6]:
tf.rank(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
tensor2.shape

TensorShape([2, 2])

In [15]:
zeros1 = tf.zeros([5,3,3])
print(zeros1)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(5, 3, 3), dtype=float32)


In [21]:
zeros1_shape =tf.reshape(zeros1,[9,-1])
print(zeros1_shape)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(9, 5), dtype=float32)
